# {{WIKI_TITLE}} — Conventions (SPEC)

This document describes how **{{OWNER}}'s** wiki is organized, so that {{OWNER}} — or any
helper, human or AI — can read and maintain it consistently. It is the "schema" layer of an
[LLM-Wiki](https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f) and conforms
to the [Open Knowledge Format (OKF)](https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md).

Generated by the `wiki-creator` skill on {{GENERATED_AT}}. Maintained day-to-day by the
`{{WIKI_NAME}}` skill.

## What this wiki is for

{{WIKI_DESCRIPTION}}

## Structure

{{STRUCTURE}}

Every folder has an `index.md` (its table of contents) and a `log.md` (its change history).
Those two filenames are **reserved** — never use them for a normal page. `README.md` and
this `SPEC.md` are the wiki's two meta documents.

## Page types

Every page — except `index.md`, `log.md`, `README.md`, and this `SPEC.md` — carries a
`type` in its frontmatter. The types used in this wiki:

{{TYPE_VOCAB_TABLE}}

## Frontmatter

Every concept page starts with a YAML block:

```yaml
---
type: <one of the types above>      # required (OKF)
title: "Human title"
description: "One-sentence summary."
timestamp: 2026-06-15T14:30:00      # ISO 8601, last change
tags: [tag1, tag2]
# plus type-specific fields: source, people, status, owner, due, follows_up, …
---
```

Only `type` is strictly required. The rest is recommended — it makes search and review
better. Unknown fields are always preserved.

## Links — {{LINK_STYLE}}

{{LINK_STYLE_DESC}}

## How this wiki is fed (the heart of it)

{{FLOW_DESC}}

## Archiving — nothing is deleted

When a page is superseded by newer knowledge, it is **archived, not deleted**. The page keeps
its file and path (so existing links still resolve), gains `archived: <date>` and
`archived_reason:` in its frontmatter, and its bullet in `index.md` moves to an `## Archived`
section. Archived pages stay searchable but are treated as historical (de-prioritized in
answers). Archiving is fully reversible, and the `{{WIKI_NAME}}` skill does it for you when
something gets replaced — so the wiki's history is never lost.

## Naming & dates

- Filenames: lowercase, hyphen-separated, no spaces (e.g. `q3-pricing.md`).
- Dated pages: prefix with `YYYY-MM-DD` (e.g. `2026-06-15-founder-sync.md`).
- Dates in frontmatter are ISO (`YYYY-MM-DD` or full ISO 8601 timestamps).

## Search

{{QMD_STATUS}}

## Health

Run `/{{WIKI_NAME}} lint` to check the wiki for missing `type`, broken links, pages absent
from their `index.md`, and stale pages. See the `{{WIKI_NAME}}` skill for all operations.
