# {{WIKI_TITLE}} — Conventions (SPEC)

This document describes how **{{OWNER}}'s** wiki is organized, so that {{OWNER}} — or any
helper, human or AI — can read and maintain it consistently. It is the "schema" layer of an
[LLM-Wiki](https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f) and conforms
to the [Open Knowledge Format (OKF)](https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md).

Generated by the `wiki-creator` skill on {{GENERATED_AT}}. Maintained day-to-day by the
`{{WIKI_NAME}}` skill.

## What this wiki is for

{{WIKI_DESCRIPTION}}

## Structure

{{STRUCTURE}}

Every folder has an `index.md` (its table of contents) and a `log.md` (its change history).
Those two filenames are **reserved** — never use them for a normal page. `README.md` and
this `SPEC.md` are the wiki's two meta documents.

## Page types

Every page — except `index.md`, `log.md`, `README.md`, and this `SPEC.md` — carries a
`type` in its frontmatter. The types used in this wiki:

{{TYPE_VOCAB_TABLE}}

## Frontmatter

Every concept page starts with a YAML block:

```yaml
---
type: <one of the types above>      # required (OKF)
title: "Human title"
description: "One-sentence summary."
timestamp: 2026-06-15T14:30:00      # ISO 8601, last change
tags: [tag1, tag2]
# plus type-specific fields: source, people, status, owner, due, follows_up, …
---
```

Only `type` is strictly required. The rest is recommended — it makes search and review
better. Unknown fields are always preserved.

## Links — {{LINK_STYLE}}

{{LINK_STYLE_DESC}}

## The distillation flow (the heart of this wiki)

Raw material — a meeting, a 1:1, a pasted chat transcript — is captured once, then the
useful parts are pulled out into short, linkable pages:

- **Meeting / conversation** → kept in `meetings/` (or under a person in
  `people/<name>/conversations/`). Transcript handling here is **{{TRANSCRIPT_MODE}}**.
- From each, fan out to the buckets — {{BUCKETS}} — one page per item, each linking back to
  its source via `source:` and to the people involved via `people:`.
- **Results** close the loop: a result links back to the decision or actionable it came
  from (`follows_up:`), so you can trace decision → outcome.

One meeting typically creates or updates several cross-linked pages. You never file things
by hand — the `{{WIKI_NAME}}` skill does the fan-out.

## Naming & dates

- Filenames: lowercase, hyphen-separated, no spaces (e.g. `q3-pricing.md`).
- Dated pages: prefix with `YYYY-MM-DD` (e.g. `2026-06-15-founder-sync.md`).
- Dates in frontmatter are ISO (`YYYY-MM-DD` or full ISO 8601 timestamps).

## Search

{{QMD_STATUS}}

## Health

Run `/{{WIKI_NAME}} lint` to check the wiki for missing `type`, broken links, pages absent
from their `index.md`, and stale pages. See the `{{WIKI_NAME}}` skill for all operations.
